# -*- coding: utf-8 -*-
"""Untitled0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/g5garji/86b78e077d0e87e2f1417063fb4a6d94/untitled0-py.ipynb
"""

a=2 #建立變數a
a





b=3 #建立變數b
b

a+b #變數相加
a=c=2

a+b #變數相加
a=c=2

age,name=19, "kaihsun"
age

str="這是字串"

str1="kaihsun說'早安你好'"
str2='kaihsun說"早安你好"'

print("HI\n你好")
print(type(100))
print(type(10.1))
print(type("hey man,how are you"))
print(type(a))
print(type(b))
print(type(age))
print(type(name))

a,b,age,name,str